trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    pip install azure-keyvault-secrets azure-identity
  displayName: 'Install Python packages'

- script: |
    python untitled8.py
  displayName: 'Run Python script'
